### ISSUE TITLE
使用simbot v2.3.4 发送文件无法发送

### ISSUE THREAD

**Issue by AllanTian** [simple-robot/simbot-component-mirai#55]
> //发送文件
> //在线地址
> // final String file = "[CAT:file,url=http://vjs.zencdn.net/v/oceans.mp4]";
> //本地地址
> final String file = "[CAT:file,file=/Users/mr.ht/Desktop/test.mp4]";
> botManager.getDefaultBot().getSender().SENDER.sendPrivateMsg(qq, file);

发送后报以下异常

`java.lang.IllegalArgumentException: cannot found upload file target 'path'
	at love.forte.simbot.component.mirai.utils.MiraiMessageParsers.toMiraiMessageContent(MiraiMessageParser.kt:368) ~[component-mirai-2.3.4.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiMessageParsers$toMiraiMessageContent$1.invoke(MiraiMessageParser.kt:125) ~[component-mirai-2.3.4.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiMessageParsers$toMiraiMessageContent$1.invoke(MiraiMessageParser.kt:123) ~[component-mirai-2.3.4.jar:na]
	at catcode.NekoAibo.split(NekoAibo.kt:243) ~[catcode-1.0.0-BETA.1.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiMessageParsers.toMiraiMessageContent(MiraiMessageParser.kt:123) ~[component-mirai-2.3.4.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiMessageParsers.toMiraiMessageContent$default(MiraiMessageParser.kt:118) ~[component-mirai-2.3.4.jar:na]
	at love.forte.simbot.component.mirai.sender.MiraiSender.privateMsg(MiraiSender.kt:194) ~[component-mirai-2.3.4.jar:na]
	at love.forte.simbot.api.sender.Sender.privateMsg(Sender.kt:290) ~[api-2.3.4.jar:na]
	at love.forte.simbot.api.sender.Sender$sendPrivateMsg$9.invokeSuspend(Sender.kt:385) ~[api-2.3.4.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.5.0.jar:1.5.0-release-749 (1.5.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at love.forte.simbot.api.sender.Sender.sendPrivateMsg(Sender.kt:385) ~[api-2.3.4.jar:na]
	at simbot.example.cron.DrinkNotify.lambda$handler$0(DrinkNotify.java:105) ~[classes/:na]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_321]
	at simbot.example.cron.DrinkNotify.handler(DrinkNotify.java:79) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_321]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.7.jar:5.3.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_321]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_321]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_321]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_321]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_321]`

**Comment by ForteScarlet** [comment]
Duplicate https://github.com/ForteScarlet/simpler-robot/discussions/393
